// handling  the errors........

try{console.log(a)

}catch(err){
    console.log("a is not defined and error is handled..........")
}